import {
  Home,
  Building2,
  Landmark,
  ShoppingCart,
  ShoppingBag,
  ShoppingBasket,
  Utensils,
  Coffee,
  Car,
  Fuel,
  Bus,
  Train,
  Bike,
  Plane,
  Wifi,
  Phone,
  Smartphone,
  Zap,
  Droplet,
  Flame,
  Wrench,
  Hammer,
  Heart,
  Stethoscope,
  Pill,
  Dumbbell,
  Gamepad2,
  Film,
  Music,
  Book,
  GraduationCap,
  Briefcase,
  Wallet,
  PiggyBank,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Gift,
  Baby,
  Dog,
  Cat,
  Shirt,
  Scissors,
  Palette,
  Camera,
  Umbrella,
  Package,
  Tag,
  Star,
  Leaf,
  Sun,
  Snowflake,
  Plug,
  Users,
  User,
  MapPin,
  Calendar,
  Sparkles,
  Luggage,
  Ship,
  Anchor,
  Compass,
  Globe,
  Palmtree,
  Laptop,
  Monitor,
  Headphones,
  Tv,
  Printer,
  Sofa,
  Lamp,
  Bed,
  Bath,
  DoorOpen,
  Trees,
  TreePine,
  PaintRoller,
  Armchair,
  Shield,
  Receipt,
  Percent,
  Coins,
  HandCoins,
  Banknote,
  Calculator,
  ClipboardList,
  FileText,
  School,
  Backpack,
  PenTool,
  Notebook,
  Glasses,
  Syringe,
  HeartPulse,
  Cross,
  Ambulance,
  Bandage,
  Waves,
  Mountain,
  Trophy,
  PawPrint,
  Puzzle,
  Factory,
  Store,
  Warehouse,
  Recycle,
  Cake,
  PartyPopper,
  Ticket,
  Clapperboard,
  BookOpen,
  Truck,
  CarFront,
  ParkingCircle,
  HandHeart,
  Handshake,
  Scale,
  Diamond,
  Key,
  Lock,
  Watch,
  type LucideIcon,
} from 'lucide-react';
import type { Category } from '../types';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  home: Home,
  building: Building2,
  landmark: Landmark,
  cart: ShoppingCart,
  bag: ShoppingBag,
  basket: ShoppingBasket,
  utensils: Utensils,
  coffee: Coffee,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  train: Train,
  bike: Bike,
  plane: Plane,
  wifi: Wifi,
  phone: Phone,
  smartphone: Smartphone,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wrench: Wrench,
  hammer: Hammer,
  heart: Heart,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  gamepad: Gamepad2,
  film: Film,
  music: Music,
  book: Book,
  graduation: GraduationCap,
  briefcase: Briefcase,
  wallet: Wallet,
  piggybank: PiggyBank,
  creditcard: CreditCard,
  dollar: DollarSign,
  trendingup: TrendingUp,
  trendingdown: TrendingDown,
  gift: Gift,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  shirt: Shirt,
  scissors: Scissors,
  palette: Palette,
  camera: Camera,
  umbrella: Umbrella,
  package: Package,
  tag: Tag,
  star: Star,
  leaf: Leaf,
  sun: Sun,
  snowflake: Snowflake,
  plug: Plug,
  users: Users,
  user: User,
  mappin: MapPin,
  calendar: Calendar,
  sparkles: Sparkles,
  luggage: Luggage,
  ship: Ship,
  anchor: Anchor,
  compass: Compass,
  globe: Globe,
  palmtree: Palmtree,
  laptop: Laptop,
  monitor: Monitor,
  headphones: Headphones,
  tv: Tv,
  printer: Printer,
  sofa: Sofa,
  lamp: Lamp,
  bed: Bed,
  bath: Bath,
  door: DoorOpen,
  trees: Trees,
  pine: TreePine,
  paintroller: PaintRoller,
  armchair: Armchair,
  shield: Shield,
  receipt: Receipt,
  percent: Percent,
  coins: Coins,
  handcoins: HandCoins,
  banknote: Banknote,
  calculator: Calculator,
  clipboard: ClipboardList,
  filetext: FileText,
  school: School,
  backpack: Backpack,
  pentool: PenTool,
  notebook: Notebook,
  glasses: Glasses,
  syringe: Syringe,
  heartpulse: HeartPulse,
  cross: Cross,
  ambulance: Ambulance,
  bandage: Bandage,
  waves: Waves,
  mountain: Mountain,
  trophy: Trophy,
  pawprint: PawPrint,
  puzzle: Puzzle,
  factory: Factory,
  store: Store,
  warehouse: Warehouse,
  recycle: Recycle,
  cake: Cake,
  party: PartyPopper,
  ticket: Ticket,
  clapperboard: Clapperboard,
  bookopen: BookOpen,
  truck: Truck,
  carfront: CarFront,
  parking: ParkingCircle,
  handheart: HandHeart,
  handshake: Handshake,
  scale: Scale,
  diamond: Diamond,
  key: Key,
  lock: Lock,
  watch: Watch,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

/**
 * Parole chiave in italiano per ogni icona, usate dal campo di ricerca del selettore
 * icone: le chiavi interne (es. "dumbbell") sono in inglese e da sole non aiuterebbero
 * chi cerca "palestra" o "sport".
 */
export const CATEGORY_ICON_SEARCH_TERMS: Record<string, string> = {
  home: 'casa abitazione',
  building: 'edificio palazzo ufficio',
  landmark: 'banca istituzione',
  cart: 'carrello spesa supermercato',
  bag: 'borsa shopping sacchetto',
  basket: 'cestino spesa',
  utensils: 'cibo ristorante posate pranzo',
  coffee: 'caffè bar',
  car: 'auto macchina automobile',
  fuel: 'benzina carburante distributore',
  bus: 'autobus pullman trasporto pubblico',
  train: 'treno trasporto',
  bike: 'bici bicicletta ciclismo',
  plane: 'aereo volo viaggio',
  wifi: 'internet connessione',
  phone: 'telefono chiamata',
  smartphone: 'cellulare telefono',
  zap: 'elettricità corrente bolletta luce',
  droplet: 'acqua bolletta',
  flame: 'gas fuoco riscaldamento',
  wrench: 'riparazione manutenzione attrezzi',
  hammer: 'martello lavori fai da te',
  heart: 'cuore salute amore',
  stethoscope: 'medico dottore salute visita',
  pill: 'farmaco medicina farmacia',
  dumbbell: 'palestra fitness sport allenamento',
  gamepad: 'videogiochi giochi console',
  film: 'cinema film',
  music: 'musica',
  book: 'libro lettura',
  graduation: 'scuola laurea istruzione studio università',
  briefcase: 'lavoro ufficio valigetta',
  wallet: 'portafoglio soldi',
  piggybank: 'risparmio salvadanaio',
  creditcard: 'carta di credito pagamento bancomat',
  dollar: 'soldi denaro valuta',
  trendingup: 'guadagno crescita investimento',
  trendingdown: 'perdita calo investimento',
  gift: 'regalo',
  baby: 'bambino neonato figli',
  dog: 'cane animale veterinario',
  cat: 'gatto animale veterinario',
  shirt: 'vestiti abbigliamento',
  scissors: 'parrucchiere taglio forbici barbiere',
  palette: 'arte hobby pittura',
  camera: 'fotografia foto',
  umbrella: 'assicurazione pioggia ombrello',
  package: 'pacco spedizione corriere',
  tag: 'etichetta generico',
  star: 'preferito stella',
  leaf: 'natura giardino ecologia',
  sun: 'estate sole vacanza',
  snowflake: 'inverno neve freddo',
  plug: 'elettronica corrente spina',
  users: 'famiglia gruppo persone',
  user: 'persona account profilo',
  mappin: 'luogo posizione viaggio',
  calendar: 'calendario appuntamento data',
  sparkles: 'pulizia bellezza extra',
  luggage: 'valigia bagaglio viaggio',
  ship: 'nave crociera barca',
  anchor: 'ancora nautica barca',
  compass: 'bussola viaggio esplorazione',
  globe: 'mondo viaggio internazionale',
  palmtree: 'vacanza palma mare',
  laptop: 'computer portatile lavoro',
  monitor: 'schermo computer',
  headphones: 'cuffie musica audio',
  tv: 'televisione intrattenimento',
  printer: 'stampante ufficio',
  sofa: 'divano arredamento casa',
  lamp: 'lampada arredamento luce',
  bed: 'letto camera arredamento',
  bath: 'bagno vasca',
  door: 'porta casa',
  trees: 'giardino natura alberi',
  pine: 'albero natura giardino',
  paintroller: 'pittura imbiancatura ristrutturazione',
  armchair: 'poltrona arredamento',
  shield: 'assicurazione protezione sicurezza',
  receipt: 'scontrino ricevuta fattura',
  percent: 'percentuale sconto tasso interesse',
  coins: 'monete soldi risparmio',
  handcoins: 'mancia donazione soldi',
  banknote: 'banconota contanti soldi',
  calculator: 'calcolatrice calcolo tasse',
  clipboard: 'lista appunti documenti',
  filetext: 'documento file contratto',
  school: 'scuola istruzione',
  backpack: 'zaino scuola',
  pentool: 'disegno penna design',
  notebook: 'quaderno appunti scuola',
  glasses: 'occhiali vista ottico',
  syringe: 'vaccino siringa medico',
  heartpulse: 'salute battito medico',
  cross: 'farmacia pronto soccorso medico',
  ambulance: 'ambulanza emergenza medico',
  bandage: 'cerotto medicazione medico',
  waves: 'mare nuoto spiaggia piscina',
  mountain: 'montagna escursione viaggio',
  trophy: 'sport vittoria premio',
  pawprint: 'animale zampa veterinario',
  puzzle: 'giochi bambini passatempo',
  factory: 'fabbrica industria lavoro',
  store: 'negozio shopping',
  warehouse: 'magazzino deposito',
  recycle: 'riciclo ecologia rifiuti',
  cake: 'torta festa compleanno',
  party: 'festa celebrazione',
  ticket: 'biglietto evento spettacolo',
  clapperboard: 'cinema film spettacolo',
  bookopen: 'lettura libro studio',
  truck: 'camion trasloco trasporto',
  carfront: 'auto macchina',
  parking: 'parcheggio sosta',
  handheart: 'beneficenza donazione volontariato',
  handshake: 'accordo contratto lavoro',
  scale: 'legale avvocato giustizia tasse',
  diamond: 'gioielli lusso prezioso',
  key: 'chiavi casa sicurezza',
  lock: 'sicurezza lucchetto protezione',
  watch: 'orologio accessorio tempo',
};

export const DEFAULT_CATEGORY_ICON = 'tag';

export const CATEGORY_COLOR_PALETTE = [
  '#6366f1', // indigo
  '#ec4899', // pink
  '#f59e0b', // amber
  '#10b981', // emerald
  '#3b82f6', // blue
  '#ef4444', // red
  '#8b5cf6', // violet
  '#14b8a6', // teal
  '#f97316', // orange
  '#84cc16', // lime
  '#06b6d4', // cyan
  '#d946ef', // fuchsia
  '#eab308', // yellow
  '#22c55e', // green
  '#0ea5e9', // sky
  '#f43f5e', // rose
];

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) >>> 0;
  }
  return h;
}

/** Colore deterministico (stabile) per una qualsiasi chiave testuale, es. una valuta. */
export function colorForKey(key: string): string {
  return CATEGORY_COLOR_PALETTE[hashString(key) % CATEGORY_COLOR_PALETTE.length];
}

/** Colore assegnato alla categoria, oppure uno deterministico (stabile) se non impostato. */
export function getCategoryColor(category: Pick<Category, 'id' | 'color'> | null | undefined): string {
  if (!category) return CATEGORY_COLOR_PALETTE[0];
  if (category.color) return category.color;
  return CATEGORY_COLOR_PALETTE[hashString(category.id) % CATEGORY_COLOR_PALETTE.length];
}

/** Icona assegnata alla categoria, oppure quella di default se non impostata. */
export function getCategoryIconKey(category: Pick<Category, 'icon'> | null | undefined): string {
  return category?.icon && CATEGORY_ICONS[category.icon] ? category.icon : DEFAULT_CATEGORY_ICON;
}

export function getCategoryIconComponent(category: Pick<Category, 'icon'> | null | undefined): LucideIcon {
  return CATEGORY_ICONS[getCategoryIconKey(category)];
}
